num1= int(input("Enter first number:"))
num2= int(input("Enter second number:"))
print(f"Sum: {num1 + num2}")
print(f"Difference: {num1 - num2}")
print(f"product: {num1 * num2}")
print(f"Division: {num1/num2}")